"""change country nullable

Revision ID: e949516045e1
Revises: 3633a6f97417
Create Date: 2025-02-24 16:58:03.810598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e949516045e1'
down_revision: Union[str, None] = '3633a6f97417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_history')
    op.alter_column('cities', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('alembic_version_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('alembic_version', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('prev_alembic_version', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('operation_direction', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('user_version', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('COALESCE(alembic_version, prev_alembic_version) IS NOT NULL', name='alembic_versions_nonnull'),
    sa.PrimaryKeyConstraint('id', name='alembic_version_history_pkey')
    )
    # ### end Alembic commands ###
